name: Dispatch Create Feedstock Request

on:
  pull_request_target:
    branches:
      - master
    paths:
      - 'recipes/**'
    types: [closed]

jobs:
  dispatch-create-feedstock-request:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: '${{ github.event.pull_request.number }}'
      IS_DEV: "${{ contains(github.event.pull_request.labels.*.name, 'dev') }}"
    steps:
      - name: dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT }}
          repository: pangeo-forge/registrar
          event-type: create-feedstock
          client-payload: '{"pr_number": "${{ env.PR_NUMBER }}", "is_dev": "${{ env.IS_DEV }}"}'
