name: Process PR Recipe

on:
  pull_request: 
    branches: master

jobs:
  process-recipe:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - id: changed-files
        name: Get the files changed in the Pull Request
        uses: jitterbit/get-changed-files@v1
        continue-on-error: true

      - name: Download bakeries.yaml
        id: download_bakeries
        run: |
          curl https://raw.githubusercontent.com/pangeo-forge/bakery-database/main/bakeries.yaml -o ${GITHUB_WORKSPACE}/bakeries.yaml

      - name: Locate Pull Requests meta.yaml
        id: meta
        run: |
          for changed_file in ${{ steps.changed-files.outputs.all }}; do
            if [[ ${changed_file} =~ ^.*recipes\/.*meta\.(yml|yaml)$ ]];
            then
              echo "::set-output name=META_YAML::${changed_file}";
              exit 0
            fi
          done
          exit 1 # Fail - meta.yaml required

      - name: Process Pull Requests recipe
        if: ${{ steps.meta.outputs.META_YAML != null }}
        uses: ./.github/actions/process_recipe
        with:
          path_to_meta_yaml: ${{ steps.meta.outputs.META_YAML }}
          path_to_bakeries_yaml: bakeries.yaml
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
          PREFECT__CLOUD__AUTH_TOKEN: ${{ secrets.PREFECT__CLOUD__AUTH_TOKEN }}

